export const featuresList = [
    {1: 'Getting a random photo'},
    {1: 'Generating tiles with pictures'},
    {1: 'Searching by keywords'},
    {1: 'If the image description is too high, you can scroll it'},
    {1: 'Zooming and downloading a pictures'},
    {1: "Author's name"},
    {1: "Author's Instagram profile"},
    {1: '"Loading more" button'},
    {1: 'Search modal'},
    {1: 'Starts searching after text input editing'},
    {1: 'Getting base color from Random Picture for colored bars'},
    {1: 'Color randomizer'},
    {1: 'Color inverter'},
    {1: 'API shoots saver'},
    {1: 'Simple input validation'},
    {1: 'No internet checker and error boundary'},
];